server:
    server.port=8080

spring:
    application:
        name: discovery-service
eureka:
    instance:
        homePageUrl: https://localhost:${server.port}
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
